# Build settings
incremental: true
permalink: /blog/:year/:title/
markdown: kramdown
highlighter: pygments
plugins: [jekyll-paginate-v2]

pagination:
  enabled: true
  per_page: 3
  permalink: "/page/:num/"

comments: true

source: source
destination: _site
sass:
  sass_dir: _sass
  style: compressed # expanded

# SEO settings
title: end2end
description: "End2End Systems, the company site"
keywords: ".net, .net core, angular, react, vuejs, javascript, typescript, nodejs, python, django, flask, ruby on rails, jekyll, azure, aws, digital solutions, technology company, custom software development, AI Companion, AI solutions, end-to-end delivery, quality software, innovation in technology"
url: https://end2end-systems.github.io/
baseurl: "/end2end"

google_analytics: UA-52446115-1
repo: http://github.com/End2End-Systems/End2End-Systems.github.io
disqus_shortname: "End2End-Systems"
disqus_site_shortname: "End2End-Systems"

# Author settings
author:
  name: End2End Systems
  logo: End2End <small>Systems</small>
  job: Technology company specialized in digital solutions
  bio: "End2End Systems is a technology company specialized in developing custom digital solutions, focusing on quality, innovation, and end-to-end delivery."
  thumb: /images/logo.svg
  email: end2endsystems@gmail.com
  url: https://End2End-Systems.github.io/
  github: https://github.com/End2End-Systems
  twitter: https://twitter.com/End2End-Systems
  facebook: https://facebook.com/End2End-Systems
  linkedin: https://linkedin.com/in/End2End-Systems

# navbar pages
navbar:
  - slug: about
    title: About
  # - slug: icons
  #   title: Icons
  # - slug: blog
  #   title: Blog

exclude: ["config.rb", "src", "Gemfile", "Gemfile.lock", "package.json","README.md", "Rakefile"]
