# Build settings
incremental: true
permalink: /blog/:year/:title/
markdown: kramdown
highlighter: pygments
plugins: [jekyll-paginate-v2]

pagination:
  enabled: true
  per_page: 3
  permalink: "/page/:num/"

comments: true

source: source
destination: _site
sass:
  sass_dir: _sass
  style: compressed # expanded

# SEO settings
title: end2end
description: "A free Jekyll theme for download"
keywords: "Jekyll, theme, free, download, SEO, blog, web"
url: http://nandomoreira.me
baseurl: "/end2end"

google_analytics: UA-52446115-1
repo: http://github.com/nandomoreirame/end2end
disqus_shortname: "nandothemes"
disqus_site_shortname: "nandothemes"

# Author settings
author:
  name: End 2 End Systems
  logo: End 2 End <small>Systems</small>
  job: Technology company specialized in digital solutions
  bio: "End2End Systems is a technology company specialized in developing custom digital solutions, focusing on quality, innovation, and end-to-end delivery."
  thumb: /images/author.jpg
  email: end2endsystems@gmail.com
  url: https://End2End-Systems.github.io/
  github: https://github.com/End2End-Systems
  twitter: https://twitter.com/End2End-Systems
  facebook: https://facebook.com/End2End-Systems
  linkedin: https://linkedin.com/in/End2End-Systems

# navbar pages
navbar:
  - slug: about
    title: About
  # - slug: icons
  #   title: Icons
  - slug: blog
    title: Blog

exclude: ["config.rb", "src", "Gemfile", "Gemfile.lock", "package.json","README.md", "Rakefile"]
